### ISSUE TITLE
Expose clear() from `electron-store`

### ISSUE THREAD

**Issue by skew202** [vue-electron/vuex-electron#10]
Would be nice to be able to reset store for development purposes.
https://github.com/sindresorhus/electron-store#clear

**Comment by GregShanken** [comment]
Hi @skew202! Have you come up with a solution to this problem?

**Comment by blastoy** [comment]
```javascript
import Store from 'electron-store';
const store = new Store({ name: 'vuex' });
store.clear();
```

**Comment by MrEmelianenko** [comment]
https://github.com/vue-electron/vuex-electron/issues/44
