### ISSUE TITLE
Type error if using vue-cli without proper webpack config

### ISSUE THREAD

**Issue by ztoben** [vue-electron/vuex-electron#11]
You may want to consider updating the readme to cover an error I was running into. Even though it's not caused by this package, it may be helpful for troubleshooting.

I had bootstrapped my project with `vue-cli` and was seeing this error after adding the `createPersistedState` to my store:

```js
TypeError: fs.existsSync is not a function at getElectronPath
```

I believe this is caused by referencing electron outside of the `main.js` file.

I fixed it by adding this to my `vue.config.js` in order to set my target properly:

```js
configureWebpack: config => {
  config.target = "electron-renderer";
}
```

**Comment by MrEmelianenko** [comment]
https://github.com/vue-electron/vuex-electron/issues/44
