### ISSUE TITLE
main process and renderer process save the same json data to disk

### ISSUE THREAD

**Issue by gaodeng** [vue-electron/vuex-electron#15]
https://github.com/vue-electron/vuex-electron/blob/297e7fa9d2c94ea047ae157336529e8d4c418b70/src/persisted-state.js#L107

may be  change to  
```js
!electron.remote && persistedState.subscribeOnChanges() 
```

**Comment by MrEmelianenko** [comment]
@gaodeng could you please provide a little bit more information about the issue?

**Comment by gaodeng** [comment]
PR https://github.com/vue-electron/vuex-electron/pull/20
