### ISSUE TITLE
Move electron from `dependencies` to `devDependencies`

### ISSUE THREAD

**Issue by jzj1993** [vue-electron/vuex-electron#16]
I'm using electron-vue to build my application. And I encountered a problem that the `.app` and DMG file is too large after build with electron-builder. 

The problem has been described here
https://github.com/electron-userland/electron-builder/issues/3573

Finally I found the reason is that vuex-electron declares a dependency of electron. So I think it may be better if move electron from `dependencies` to `devDependencies`.

**Comment by davestewart** [comment]
Perhaps it should be a peer dependency?

- https://nodejs.org/en/blog/npm/peer-dependencies/#the-solution-peer-dependencies

**Comment by MrEmelianenko** [comment]
@jzj1993 @davestewart thank you for the suggestions, functionality will be released soon.

Commit: https://github.com/vue-electron/vuex-electron/commit/e8c77a33b2c8c5a91570192723067254c5cc14ef
