### ISSUE TITLE
Q: Is there any particular caveats to change persistance library?

### ISSUE THREAD

**Issue by MaverickMartyn** [vue-electron/vuex-electron#21]
I was considering changing my vuex persistence package, since the blacklist feature (which I badly need) is currently broken.
I would just like to know of any suggestions as to which alternate package to use, as well as anything I should look out for etc.

Thanks.

**Comment by NoelDavies** [comment]
@MaverickMartyn , I'm using yours.. haha.

I just swapped it out directly in the package.json file like so:
```json
{
  ...,
  "vuex-electron": "github:MaverickMartyn/vuex-electron#cc7a5a923"
}```

**Comment by MaverickMartyn** [comment]
I figured it out on my own, but forgot to close this. Sorry about that. :)
