### ISSUE TITLE
Is Data Stored in my Vuex when i build electron app and then close it?

### ISSUE THREAD

**Issue by thesogafoi** [vue-electron/vuex-electron#36]
Hey Guys i'm so confusing i want to build an electron app whit vue an vuex i have two questions

1) if i close app (for example turn off my pc and after few days turn on it and open the app again ) , all data saved to vuex or not ? need i use databases like sqlite to store data from vuex?

2) i want to have two databases localdatabase and online database i can handle online database but how can i share some localdatabase to server for example i add two project to my local database and i want send second projects'data with axios to server how can i handle this i should to have sqlite-vuex-vue-electron or i can handle it with vuex-vue-electron

**Comment by Zyles** [comment]
Vuex is a state management for the session, it is not persistent. Either save and load the state on disk in JSON files or in a database such as SQLite.

**Comment by JoacoEsteban** [comment]
Is this so? I see that part of the store is persistent and is maintained across builds.

**Comment by Zyles** [comment]
Vuex by default does not, but with this library if you use the createPersistentState option it will save the store in AppData.

**Comment by MrEmelianenko** [comment]
https://github.com/vue-electron/vuex-electron/issues/44

**Comment by koibi2** [comment]
> createPersistentState

it should be `createPersistedState`

**Comment by ISMAILRAMZAN** [comment]
after build electron app the createPersistedState does'nt store data after closing app. have any idea about this type of error why data is no stored when we use createPersistedState in electron-vue app. if any one tell me i will apreatiate him please! soon reply
