### ISSUE TITLE
Locally stored state doesn't get updated and causes weird merges

### ISSUE THREAD

**Issue by daniandl** [vue-electron/vuex-electron#46]
I'm writing this mostly as a warning, as I lost hours debugging this...
(I'm using the base Vue Electron boilerplate from CLI3.)

My project started with a `store.js` file, I converted it to a folder with an index.js and a vuex module for better organization.

I imported the store to my electron's main process file (background.js) and `console.log` to see that the state from my old and *deleted* `store.js` is still present in the main process. One of my modules has the same name as one of the old properties, so that's causing issues..

I assume this all has something to do with `electron-store` saving the store locally, but this can't be the intended use... can it?

EDIT: Well I seem to have a thing for solving my own problems the second I open an issue, it was indeed due to the `vuex.json` file in my app's `userData` folder.. I did further tests and found out that changing my vuex state in any way while developing didn't change the local version. I dont know if this is intended, but I can't work with inconsistencies like this.. Hope I saved someone some time :)

**Comment by baruchiro** [comment]
Where is the `userData` folder you talking about?

**Comment by daniandl** [comment]
https://electronjs.org/docs/api/app#appgetpathname

**Comment by weifu2** [comment]
I meet the same problem，I want to clear vuex.json in my `userData` folder，how do you solve it？

**Comment by daniandl** [comment]
@weifu2 I ended up not using this library, so I don't know sorry.
I switched to purely using IPC.
