### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by shealan** [vue-electron/vuex-electron#6]
This appears to be the holy grail 😮 (sharing of store between processes) but the lack of example code leaves me wondering how it works. How do you access store data and fire actions from the main process? I'd love to know if anyone has any example code online?

**Comment by MrEmelianenko** [comment]
@shealan glad to hear this. I'll add some examples on this weekend 😉

**Comment by shealan** [comment]
> @shealan glad to hear this. I'll add some examples on this weekend 😉

Thank you so much! I have so many projects to use this on. Very exciting indeed.
