### ISSUE TITLE
How to rehydrate after restarting or reloading.

### ISSUE THREAD

**Issue by michaelmano** [vue-electron/vuex-electron#66]
This is more of a question as I cant find any information on it or dont know what im looking for, I have a basic app. Im wanting to know how to rehydrate the state after the application is restarted or closed.

my store is using the following:
```
plugins: [
    createPersistedState(),
    createSharedMutations(),
  ],
```
and my main is importing the store but when the application reboots the store is blank again.

**Comment by michaelmano** [comment]
Don't worry. for some odd reason this only works if my actions are all uppercase.

**Comment by NoelDavies** [comment]
I was going to say, you could always persist to localstorage instead?
