### ISSUE TITLE
handle error in dispatch

### ISSUE THREAD

**Issue by fikrihanda** [vue-electron/vuex-electron#7]
how to handle error in dispatch ? i want build promise in dispatch but error trigger in main process how to handle in renderer process ?

**Comment by MrEmelianenko** [comment]
Hi @fikrihanda,

This isn't possible because all actions are performing in the main process.

Best Regards,
Andrew

**Comment by fikrihanda** [comment]
i see i think need store error for handle thx for response @MrEmelianenko
